<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 4 Le salaire de Belges | Introduction à R et aux statistiques en sciences sociales</title>
  <meta name="description" content="Ceci est une introduction au langage de programmation R et à l’analyse statistique en sciences sociales." />
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 4 Le salaire de Belges | Introduction à R et aux statistiques en sciences sociales" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Ceci est une introduction au langage de programmation R et à l’analyse statistique en sciences sociales." />
  <meta name="github-repo" content="https://github.com/L3vL/intro_r_code" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 4 Le salaire de Belges | Introduction à R et aux statistiques en sciences sociales" />
  
  <meta name="twitter:description" content="Ceci est une introduction au langage de programmation R et à l’analyse statistique en sciences sociales." />
  

<meta name="author" content="Lev Lhommeau" />


<meta name="date" content="2023-02-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="charge_code_filtrer.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.27/datatables.js"></script>
<link href="libs/dt-core-1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.12.1/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.12.1/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction à R et aux statistiques en sciences sociales</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Remarques préliminaires</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#installer-r"><i class="fa fa-check"></i><b>1.1</b> Installer R</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#se-retrouver-à-lintérieur-de-ce-syllabus"><i class="fa fa-check"></i><b>1.2</b> Se retrouver à l’intérieur de ce syllabus</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Priseenmain.html"><a href="Priseenmain.html"><i class="fa fa-check"></i><b>2</b> Prise en main de R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Priseenmain.html"><a href="Priseenmain.html#Commandes"><i class="fa fa-check"></i><b>2.1</b> Commandes dans R</a></li>
<li class="chapter" data-level="2.2" data-path="Priseenmain.html"><a href="Priseenmain.html#Fonctions_aides"><i class="fa fa-check"></i><b>2.2</b> Fonctions et aide dans R</a></li>
<li class="chapter" data-level="2.3" data-path="Priseenmain.html"><a href="Priseenmain.html#working_directory"><i class="fa fa-check"></i><b>2.3</b> Espace de travail (<em>working directory</em>)</a></li>
<li class="chapter" data-level="2.4" data-path="Priseenmain.html"><a href="Priseenmain.html#packages"><i class="fa fa-check"></i><b>2.4</b> Installer et lancer des <em>packages</em> (bibliothèques)</a></li>
<li class="chapter" data-level="2.5" data-path="Priseenmain.html"><a href="Priseenmain.html#objets_envir"><i class="fa fa-check"></i><b>2.5</b> Objets et environnement dans R</a></li>
<li class="chapter" data-level="2.6" data-path="Priseenmain.html"><a href="Priseenmain.html#import_donnees"><i class="fa fa-check"></i><b>2.6</b> Importer et enregistrer des données</a></li>
<li class="chapter" data-level="2.7" data-path="Priseenmain.html"><a href="Priseenmain.html#close_R"><i class="fa fa-check"></i><b>2.7</b> Fermer R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="charge_code_filtrer.html"><a href="charge_code_filtrer.html"><i class="fa fa-check"></i><b>3</b> Charger des bases de données et les filtrer</a>
<ul>
<li class="chapter" data-level="3.1" data-path="charge_code_filtrer.html"><a href="charge_code_filtrer.html#charger-des-données-au-format-r-.rds"><i class="fa fa-check"></i><b>3.1</b> Charger des données au format R (<em>.RDS</em>)</a></li>
<li class="chapter" data-level="3.2" data-path="charge_code_filtrer.html"><a href="charge_code_filtrer.html#explorer-les-données-créer-un-codebook-interactif"><i class="fa fa-check"></i><b>3.2</b> Explorer les données: créer un <em>codebook</em> interactif</a></li>
<li class="chapter" data-level="3.3" data-path="charge_code_filtrer.html"><a href="charge_code_filtrer.html#filtrer-les-données"><i class="fa fa-check"></i><b>3.3</b> Filtrer les données</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html"><i class="fa fa-check"></i><b>4</b> Le salaire de Belges</a>
<ul>
<li class="chapter" data-level="4.1" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html#statistiques-descriptives-et-simples-graphiques-des-salaires-des-belges"><i class="fa fa-check"></i><b>4.1</b> Statistiques descriptives et simples graphiques des salaires des Belges</a></li>
<li class="chapter" data-level="4.2" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html#comparer-une-distribution-à-une-distribution-normale"><i class="fa fa-check"></i><b>4.2</b> Comparer une distribution à une distribution normale</a></li>
<li class="chapter" data-level="4.3" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html#trans_log_grspnum"><i class="fa fa-check"></i><b>4.3</b> Distribution normale et transformation logarithmique</a></li>
<li class="chapter" data-level="4.4" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html#distribution_normale_proba"><i class="fa fa-check"></i><b>4.4</b> Distribution normale et probabilités</a></li>
<li class="chapter" data-level="4.5" data-path="salaire_belge_stat_desc.html"><a href="salaire_belge_stat_desc.html#connaître-la-probabilité-des-salaires"><i class="fa fa-check"></i><b>4.5</b> Connaître la probabilité des salaires</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction à R et aux statistiques en sciences sociales</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="salaire_belge_stat_desc" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapitre 4</span> Le salaire de Belges<a href="salaire_belge_stat_desc.html#salaire_belge_stat_desc" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!-- Dans le [chapitre précédent](#charge_code_filtrer), vous avez appris à charger les données, à créer un *Codebook* et a filtrer les données. Vous avez notamment créé la base de données *ESS9_BE* dont nous aurons besoin dans ce chapitre pour mener nos analyses. -->
<p>Si vous avez fermé R depuis le dernier chapitre, il faudra lancer les <em>packages</em>. Vous pouvez le faire avec le code suivant:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="salaire_belge_stat_desc.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">&quot;pacman&quot;</span>)) <span class="fu">install.packages</span>(<span class="st">&quot;pacman&quot;</span>) <span class="co">#Cela vérifie</span></span>
<span id="cb66-2"><a href="salaire_belge_stat_desc.html#cb66-2" aria-hidden="true" tabindex="-1"></a>                             <span class="co">#si le package pacman est installé.</span></span>
<span id="cb66-3"><a href="salaire_belge_stat_desc.html#cb66-3" aria-hidden="true" tabindex="-1"></a>                             <span class="co">#S&#39;il ne l&#39;est pas, il est installé.</span></span>
<span id="cb66-4"><a href="salaire_belge_stat_desc.html#cb66-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-5"><a href="salaire_belge_stat_desc.html#cb66-5" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, descr, rcompanion, codebook,</span>
<span id="cb66-6"><a href="salaire_belge_stat_desc.html#cb66-6" aria-hidden="true" tabindex="-1"></a>               DT, sjPlot, labelled) <span class="co">#On lance les packages</span></span></code></pre></div>
<div id="statistiques-descriptives-et-simples-graphiques-des-salaires-des-belges" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Statistiques descriptives et simples graphiques des salaires des Belges<a href="salaire_belge_stat_desc.html#statistiques-descriptives-et-simples-graphiques-des-salaires-des-belges" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- Afin d'apprendre à filtrer et modifier les données et comprendre la distribution normale et les calculs de probabilités que l'on peut effectuer avec cette distribution. Cela sert notamment à comprendre les intervalles de confiances. -->
<p>Si l’on veut étudier les salaires des Belges il faut que nous continuions à travailler avec la base de données <em>ESS9_BE</em> que nous avons créée dans le <a href="charge_code_filtrer.html#charge_code_filtrer">chapitre précédent</a> précédemment qui contient exclusivement les observations belges. Par ailleurs, il faut que nous identifiions la variable de la base de données contenant les salaires. Il s’agit de la variable <em>grspnum</em>. Nous pouvons obtenir des statistiques descriptives de cette variable avec la commande <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary"><em>summary()</em></a>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="salaire_belge_stat_desc.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ESS9_BE<span class="sc">$</span>grspnum)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##       0    2019    2800    3148    3700   40000    1068</code></pre>
<p>On voit que la valeur minimale est de <span class="math inline">\(0€\)</span>, la valeur maximale de <span class="math inline">\(40000€\)</span>. La moyenne s’élève à <span class="math inline">\(3148€\)</span> tandis que la médiane est sensiblement plus basse à <span class="math inline">\(2800€\)</span>. Cela suggère qu’un nombre restreint de valeurs très élevées tirent la moyenne vers le haut. Il est à noter qu’il y a un nombre important de valeurs manquantes: <span class="math inline">\(1068\)</span>, soit <span class="math inline">\(60\%\)</span> sur les <span class="math inline">\(1767\)</span>.</p>
<p>Faisons-nous une image de cette distribution. Vu qu’il s’agit d’une variable continue, nous représentons ceci sous forme d’histogramme avec la fonction de base <a href="https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist"><em>hist()</em></a> et la fonction un peu plus avancée <a href="https://www.rdocumentation.org/packages/rcompanion/versions/2.4.21/topics/plotNormalHistogram"><em>plotNormalHistogram</em></a> du <em>package</em> <a href="https://rcompanion.org/handbook/">rcompanion</a> y ajoutant une courbe de distribution normale (“cloche”)<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a>:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="salaire_belge_stat_desc.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ESS9_BE<span class="sc">$</span>grspnum, <span class="at">breaks =</span> <span class="dv">50</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="salaire_belge_stat_desc.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotNormalHistogram</span>(ESS9_BE<span class="sc">$</span>grspnum,</span>
<span id="cb70-2"><a href="salaire_belge_stat_desc.html#cb70-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">breaks =</span> <span class="dv">50</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-48-2.png" width="672" /></p>
<p>On peut aussi faire de graphiques plus attrayants avec les fonctions du <em>package</em> <a href="https://ggplot2.tidyverse.org/"><em>ggplot2</em></a> de l’ensemble <a href="https://www.tidyverse.org/"><em>tidyverse</em></a><a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a>:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="salaire_belge_stat_desc.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ESS9_BE, <span class="fu">aes</span>(<span class="at">x=</span>grspnum)) <span class="sc">+</span></span>
<span id="cb71-2"><a href="salaire_belge_stat_desc.html#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">50</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>On voit très clairement que la plupart des valeurs sont concentrées entre <span class="math inline">\(0€\)</span> et <span class="math inline">\(5000€\)</span> et qu’au-delà de <span class="math inline">\(10000\)</span> il n’y a plus que quelques observations isolées. Celles-ci tirent la moyenne vers le haut. Un autre moyen de représenter cela est de le faire à l’aide d’une “boîte à moustache” (<em>boxplot</em>):</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="salaire_belge_stat_desc.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ESS9_BE<span class="sc">$</span>grspnum)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<p>Vous pouvez aussi la représenter à l’aide de du <em>package</em> <a href="https://ggplot2.tidyverse.org/"><em>ggplot2</em></a><a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a>:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="salaire_belge_stat_desc.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ESS9_BE, <span class="fu">aes</span>(<span class="at">x=</span>grspnum)) <span class="sc">+</span></span>
<span id="cb73-2"><a href="salaire_belge_stat_desc.html#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Les <em>boxplots</em> indiquent aussi très clairement qu’il y a quelques valeurs “extrêmes”, très élevées, qui “tirent” la moyenne vers le haut. Par ailleurs, il y a un certain nombre d’observations avec des revenus très faibles, tels que <span class="math inline">\(0€\)</span>.</p>
<p>Il nous semble utile de considérer seulement les personnes travaillant à temps plein. Par ailleurs, il faut contrôler que les données soient cohérentes. La Belgique ayant un salaire minimum, il n’est pas légalement possible pour un salarié de percevoir un salaire de moins de <span class="math inline">\(1000€\)</span> tout en travaillant à temps plein<a href="#fn31" class="footnote-ref" id="fnref31"><sup>31</sup></a>.</p>
<p>Nous nous concentrons ainsi sur les Belges travaillant plus de 34 heures pas semaine (temps plein) et gagnant plus de <span class="math inline">\(1000€\)</span> par mois, mais moins de <span class="math inline">\(15000€\)</span> par mois. La variable “<em>wkhtot</em>” indique le nombre d’heures travaillées par semaine. On utilise la fonction <a href="https://dplyr.tidyverse.org/reference/filter.html"><em>filter()</em></a> pour sélectionner les observations. On crée une nouvelle base de données nommée <em>ESS9_BE_fulltime</em>:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="salaire_belge_stat_desc.html#cb74-1" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime<span class="ot">&lt;-</span><span class="fu">filter</span>(ESS9_BE, <span class="co">#Base de donnés</span></span>
<span id="cb74-2"><a href="salaire_belge_stat_desc.html#cb74-2" aria-hidden="true" tabindex="-1"></a>                   wkhtot<span class="sc">&gt;</span><span class="dv">34</span> <span class="sc">&amp;</span> <span class="co"># Travaillant plus de 34 heures</span></span>
<span id="cb74-3"><a href="salaire_belge_stat_desc.html#cb74-3" aria-hidden="true" tabindex="-1"></a>                     grspnum<span class="sc">&gt;</span><span class="dv">1000</span> <span class="sc">&amp;</span> <span class="co"># Percevant plus de 1000€,</span></span>
<span id="cb74-4"><a href="salaire_belge_stat_desc.html#cb74-4" aria-hidden="true" tabindex="-1"></a>                     grspnum<span class="sc">&lt;</span><span class="dv">15000</span>) <span class="co"># mais moins de 15.000€.</span></span></code></pre></div>
<p>Vous pouvez vérifier cette base de données, notamment en vous assurant qu’il n’y a personne qui ravitaille moins de 35 heures et percevant moins de <span class="math inline">\(1000€\)</span> et plus de <span class="math inline">\(15000€\)</span>. Vous pouvez utiliser la fonction <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/summary"><em>summary()</em></a> pour vérifier que les variables <em>grspnum</em> et <em>wkhtot</em> dans la base de données <em>ESS9_BE_fulltime</em> ne contiennent plus que des valeurs compatibles avec le filtre que l’on vient d’appliquer:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="salaire_belge_stat_desc.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ESS9_BE_fulltime<span class="sc">$</span>grspnum)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1200    2400    2986    3365    4000   14000</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="salaire_belge_stat_desc.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ESS9_BE_fulltime<span class="sc">$</span>wkhtot)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   35.00   38.00   40.00   45.58   46.00  168.00</code></pre>
<p>Le filtrage a fonctionné: dans notre échantillon, personne ne travaille moins de 35 heures et personne ne perçoit moins de <span class="math inline">\(1000€\)</span> (le minimum est de <span class="math inline">\(1200€\)</span>) et plus de <span class="math inline">\(15000€\)</span> (le maximum est <span class="math inline">\(14000€\)</span>). Cependant, des anomalies apparaissent au niveau du temps de travail. L’on peut s’en rendre compte avec les fonctions <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table"><em>table()</em></a> et <a href="https://www.rdocumentation.org/packages/descr/versions/1.1.5/topics/freq"><em>freq()</em></a>:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="salaire_belge_stat_desc.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(ESS9_BE_fulltime<span class="sc">$</span>wkhtot)</span></code></pre></div>
<pre><code>## 
##  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  52  53  55  56  60  62  65  70  72  75  80  84 100 105 147 168 
##  19  12  13 110  18 103   9  23   9   8  67   4   3   7   1  48   1   1   8   1  24   1   6  13   2   4   3   1   1   1   1   4</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="salaire_belge_stat_desc.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(ESS9_BE_fulltime<span class="sc">$</span>wkhtot)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<pre><code>## Total hours normally worked per week in main job overtime included 
##       Frequency  Percent
## 35           19   3.6122
## 36           12   2.2814
## 37           13   2.4715
## 38          110  20.9125
## 39           18   3.4221
## 40          103  19.5817
## 41            9   1.7110
## 42           23   4.3726
## 43            9   1.7110
## 44            8   1.5209
## 45           67  12.7376
## 46            4   0.7605
## 47            3   0.5703
## 48            7   1.3308
## 49            1   0.1901
## 50           48   9.1255
## 52            1   0.1901
## 53            1   0.1901
## 55            8   1.5209
## 56            1   0.1901
## 60           24   4.5627
## 62            1   0.1901
## 65            6   1.1407
## 70           13   2.4715
## 72            2   0.3802
## 75            4   0.7605
## 80            3   0.5703
## 84            1   0.1901
## 100           1   0.1901
## 105           1   0.1901
## 147           1   0.1901
## 168           4   0.7605
## Total       526 100.0000</code></pre>
<p>Ainsi 4 répondants affirment travailler <span class="math inline">\(168\)</span> heures par semaine. Vu qu’une semaine compte <span class="math inline">\(168\)</span> heures et que l’être humain a un besoin physiologique de sommeil, ces réponses semblent aberrantes<a href="#fn32" class="footnote-ref" id="fnref32"><sup>32</sup></a>. Vue que l’analyse que nous voulons mener ne porte pas sur le temps de travail, nous n’allons ni investiguer ces cas plus en détail, ni les exclure de nos analyses.</p>
<p>La distribution de la variable dans la base de données que nous avons filtrée, se rapproche-t-elle d’une distribution normale? Analysons cela à nouveau avec les histogrammes et “boxplots”:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="salaire_belge_stat_desc.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec R de base:</span></span>
<span id="cb83-2"><a href="salaire_belge_stat_desc.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="salaire_belge_stat_desc.html#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ESS9_BE_fulltime<span class="sc">$</span>grspnum,</span>
<span id="cb83-4"><a href="salaire_belge_stat_desc.html#cb83-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">50</span>,</span>
<span id="cb83-5"><a href="salaire_belge_stat_desc.html#cb83-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Histogramme: Salaire des Belges en 2018&quot;</span>,</span>
<span id="cb83-6"><a href="salaire_belge_stat_desc.html#cb83-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Salaire des Belges en €&quot;</span>)</span>
<span id="cb83-7"><a href="salaire_belge_stat_desc.html#cb83-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-8"><a href="salaire_belge_stat_desc.html#cb83-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec ggplot2:</span></span>
<span id="cb83-9"><a href="salaire_belge_stat_desc.html#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="salaire_belge_stat_desc.html#cb83-10" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>grspnum)) <span class="sc">+</span> </span>
<span id="cb83-11"><a href="salaire_belge_stat_desc.html#cb83-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>)<span class="sc">+</span></span>
<span id="cb83-12"><a href="salaire_belge_stat_desc.html#cb83-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramme: Salaire des Belges en 2018&quot;</span>) <span class="sc">+</span></span>
<span id="cb83-13"><a href="salaire_belge_stat_desc.html#cb83-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Salaire des Belges en €&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-55-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-55-2.png" width="50%" />
Avec des <em>boxplot</em>, la variable <em>grspnum</em> donne le résultat suivant:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="salaire_belge_stat_desc.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec R de base:</span></span>
<span id="cb84-2"><a href="salaire_belge_stat_desc.html#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="salaire_belge_stat_desc.html#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ESS9_BE_fulltime<span class="sc">$</span>grspnum,</span>
<span id="cb84-4"><a href="salaire_belge_stat_desc.html#cb84-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Salaire des Belges en €&quot;</span>,</span>
<span id="cb84-5"><a href="salaire_belge_stat_desc.html#cb84-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Boîte à moustache: Salaire des Belges en 2018&quot;</span>) </span>
<span id="cb84-6"><a href="salaire_belge_stat_desc.html#cb84-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-7"><a href="salaire_belge_stat_desc.html#cb84-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec ggplot2:</span></span>
<span id="cb84-8"><a href="salaire_belge_stat_desc.html#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="salaire_belge_stat_desc.html#cb84-9" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>grspnum)) <span class="sc">+</span> </span>
<span id="cb84-10"><a href="salaire_belge_stat_desc.html#cb84-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Boîte à moustache: Salaire des Belges en 2018&quot;</span>)<span class="sc">+</span></span>
<span id="cb84-11"><a href="salaire_belge_stat_desc.html#cb84-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Boîte à moustache: Salaire des Belges en 2018&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-56-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-56-2.png" width="50%" /></p>
<p>L’histogramme et la boîte à moustache montrent une distribution moins “écrasée”. Elle reste cependant asymétrique avec des valeurs très élevées – et une “coupure” vers le bas à <span class="math inline">\(1200€\)</span>. La distribution semble donc toujours loin d’être normale.</p>
</div>
<div id="comparer-une-distribution-à-une-distribution-normale" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Comparer une distribution à une distribution normale<a href="salaire_belge_stat_desc.html#comparer-une-distribution-à-une-distribution-normale" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Visuellement, la distribution de la variable des salaires (<em>grspnum</em>) ne semble pas normale. Essayons d’objectiver cela. Nous rappelons quelques caractéristiques d’une distribution normale:</p>
<ul>
<li>la distribution est symétrique;</li>
<li>moyenne <span class="math inline">\(=\)</span> médiane <span class="math inline">\(=\)</span> mode;</li>
<li><span class="math inline">\(\approx68\%\)</span> des observations se trouvent dans l’intervalle entre <span class="math inline">\(-1\)</span> écart type (<span class="math inline">\(\sigma\)</span>) et <span class="math inline">\(+1\)</span> écart type (<span class="math inline">\(\sigma\)</span>) de la moyenne (<span class="math inline">\(\mu\)</span>): <span class="math inline">\([\mu-\sigma;\mu+\sigma]\)</span></li>
<li><span class="math inline">\(\approx95\%\)</span> des observations se trouvent dans l’intervalle entre <span class="math inline">\(-1,96\)</span> écart type (<span class="math inline">\(\sigma\)</span>) et <span class="math inline">\(+1,96\)</span> écart type (<span class="math inline">\(\sigma\)</span>) de la moyenne (<span class="math inline">\(\mu\)</span>): <span class="math inline">\([\mu-1,96\sigma;\mu+1,96\sigma]\)</span></li>
<li><span class="math inline">\(\approx95,5\%\)</span> des observations se trouvent dans l’intervalle entre <span class="math inline">\(-2\)</span> écart type (<span class="math inline">\(\sigma\)</span>) et <span class="math inline">\(+2\)</span> écart type (<span class="math inline">\(\sigma\)</span>) de la moyenne (<span class="math inline">\(\mu\)</span>): <span class="math inline">\([\mu-2\sigma;\mu+2\sigma]\)</span></li>
<li><span class="math inline">\(\approx2,5\%\)</span> des observation sont supérieures à <span class="math inline">\(1,96\)</span> écart type (<span class="math inline">\(\sigma\)</span>) de la moyenne (<span class="math inline">\(\mu\)</span>): <span class="math inline">\([\mu+1,96\sigma;+\infty)\)</span></li>
<li><span class="math inline">\(\approx2,5\%\)</span> des observation inférieurs à <span class="math inline">\(-1,96\)</span> écart type (<span class="math inline">\(\sigma\)</span>) de la moyenne (<span class="math inline">\(\mu\)</span>): <span class="math inline">\([\mu-1,96\sigma;-\infty)\)</span></li>
</ul>
<p>La fonction <em>nonantecinq()</em> que nous définissions permet de comparer la distribution d’une variable avec les caractéristiques d’une distribution normale. Pour définir une nouvelle fonction, il faut utiliser la fonction <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/function"><em>fonction()</em></a><a href="#fn33" class="footnote-ref" id="fnref33"><sup>33</sup></a>:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="salaire_belge_stat_desc.html#cb85-1" aria-hidden="true" tabindex="-1"></a>nonantecinq<span class="ot">&lt;-</span><span class="cf">function</span>(x){</span>
<span id="cb85-2"><a href="salaire_belge_stat_desc.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On exclut les valeurs manquantes de la variable analysée</span></span>
<span id="cb85-3"><a href="salaire_belge_stat_desc.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  x1<span class="ot">&lt;-</span>x[<span class="fu">is.na</span>(x)<span class="sc">!=</span>T]</span>
<span id="cb85-4"><a href="salaire_belge_stat_desc.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On calcule l&#39;effectif total</span></span>
<span id="cb85-5"><a href="salaire_belge_stat_desc.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  x1_l1<span class="ot">&lt;-</span><span class="fu">length</span>(x[<span class="fu">is.na</span>(x)<span class="sc">!=</span>T])</span>
<span id="cb85-6"><a href="salaire_belge_stat_desc.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On calcule l&#39;effectif se situant à -1,96 écart types de la moyenne</span></span>
<span id="cb85-7"><a href="salaire_belge_stat_desc.html#cb85-7" aria-hidden="true" tabindex="-1"></a>  x1_low<span class="ot">&lt;-</span><span class="fu">length</span>(x1[x1 <span class="sc">&lt;</span> <span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T)])</span>
<span id="cb85-8"><a href="salaire_belge_stat_desc.html#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On calcule l&#39;effectif se situant à +1,96 écart types de la moyenne</span></span>
<span id="cb85-9"><a href="salaire_belge_stat_desc.html#cb85-9" aria-hidden="true" tabindex="-1"></a>  x1_high<span class="ot">&lt;-</span><span class="fu">length</span>(x1[x1 <span class="sc">&gt;</span> <span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T)])</span>
<span id="cb85-10"><a href="salaire_belge_stat_desc.html#cb85-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On calcule l&#39;effectif se situant à -1 écarts types de la moyenne (point d&#39;inflexion si normal)</span></span>
<span id="cb85-11"><a href="salaire_belge_stat_desc.html#cb85-11" aria-hidden="true" tabindex="-1"></a>  x1_low_inflex<span class="ot">&lt;-</span><span class="fu">length</span>(x1[x1 <span class="sc">&lt;</span> <span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">-</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T)])</span>
<span id="cb85-12"><a href="salaire_belge_stat_desc.html#cb85-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#On calcule l&#39;effectif se situant à +1 écart types de la moyenne (point d&#39;inflexion si normal)</span></span>
<span id="cb85-13"><a href="salaire_belge_stat_desc.html#cb85-13" aria-hidden="true" tabindex="-1"></a>  x1_high_inflex<span class="ot">&lt;-</span><span class="fu">length</span>(x1[x1 <span class="sc">&gt;</span> <span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">+</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T)])</span>
<span id="cb85-14"><a href="salaire_belge_stat_desc.html#cb85-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb85-15"><a href="salaire_belge_stat_desc.html#cb85-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Pourcentages:</span></span>
<span id="cb85-16"><a href="salaire_belge_stat_desc.html#cb85-16" aria-hidden="true" tabindex="-1"></a>  pourcent_bas<span class="ot">&lt;-</span>x1_low<span class="sc">/</span>x1_l1</span>
<span id="cb85-17"><a href="salaire_belge_stat_desc.html#cb85-17" aria-hidden="true" tabindex="-1"></a>  pourcent_haut<span class="ot">&lt;-</span>x1_high<span class="sc">/</span>x1_l1</span>
<span id="cb85-18"><a href="salaire_belge_stat_desc.html#cb85-18" aria-hidden="true" tabindex="-1"></a>  pourcent_1<span class="fl">.96</span><span class="ot">&lt;-</span>(<span class="dv">1</span><span class="sc">-</span>(pourcent_bas<span class="sc">+</span>pourcent_haut))<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb85-19"><a href="salaire_belge_stat_desc.html#cb85-19" aria-hidden="true" tabindex="-1"></a>  pourcent_inflex_bas<span class="ot">&lt;-</span>x1_low_inflex<span class="sc">/</span>x1_l1</span>
<span id="cb85-20"><a href="salaire_belge_stat_desc.html#cb85-20" aria-hidden="true" tabindex="-1"></a>  pourcent_inflex_haut<span class="ot">&lt;-</span>x1_high_inflex<span class="sc">/</span>x1_l1</span>
<span id="cb85-21"><a href="salaire_belge_stat_desc.html#cb85-21" aria-hidden="true" tabindex="-1"></a>  pourcent_1_inflex<span class="ot">&lt;-</span>(<span class="dv">1</span><span class="sc">-</span> (pourcent_inflex_bas <span class="sc">+</span> pourcent_inflex_haut))<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb85-22"><a href="salaire_belge_stat_desc.html#cb85-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb85-23"><a href="salaire_belge_stat_desc.html#cb85-23" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Mode(s)</span></span>
<span id="cb85-24"><a href="salaire_belge_stat_desc.html#cb85-24" aria-hidden="true" tabindex="-1"></a>  mode_func <span class="ot">&lt;-</span> <span class="cf">function</span>(x_1) {                    </span>
<span id="cb85-25"><a href="salaire_belge_stat_desc.html#cb85-25" aria-hidden="true" tabindex="-1"></a>    modes_multi<span class="ot">&lt;-</span><span class="fu">which</span>(<span class="fu">table</span>(x_1)<span class="sc">==</span><span class="fu">max</span>(<span class="fu">table</span>(x_1)))</span>
<span id="cb85-26"><a href="salaire_belge_stat_desc.html#cb85-26" aria-hidden="true" tabindex="-1"></a>    mode_final<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">names</span>(modes_multi))</span>
<span id="cb85-27"><a href="salaire_belge_stat_desc.html#cb85-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(mode_final)</span>
<span id="cb85-28"><a href="salaire_belge_stat_desc.html#cb85-28" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb85-29"><a href="salaire_belge_stat_desc.html#cb85-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb85-30"><a href="salaire_belge_stat_desc.html#cb85-30" aria-hidden="true" tabindex="-1"></a>  mode_calc<span class="ot">&lt;-</span><span class="fu">mode_func</span>(x)</span>
<span id="cb85-31"><a href="salaire_belge_stat_desc.html#cb85-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb85-32"><a href="salaire_belge_stat_desc.html#cb85-32" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Affichage des résultats</span></span>
<span id="cb85-33"><a href="salaire_belge_stat_desc.html#cb85-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="fu">paste</span>(<span class="st">&quot; Moyenne=&quot;</span>,<span class="fu">round</span>(<span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-34"><a href="salaire_belge_stat_desc.html#cb85-34" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Écart type=&quot;</span>,<span class="fu">round</span>(<span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-35"><a href="salaire_belge_stat_desc.html#cb85-35" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Médiane=&quot;</span>,<span class="fu">round</span>(<span class="fu">median</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-36"><a href="salaire_belge_stat_desc.html#cb85-36" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Mode (si multiples, le plus faible)=&quot;</span>,<span class="fu">ifelse</span>(<span class="fu">length</span>(mode_calc)<span class="sc">&gt;</span><span class="dv">1</span>, <span class="fu">round</span>(mode_calc[<span class="dv">1</span>],<span class="dv">2</span>), <span class="fu">round</span>(mode_calc,<span class="dv">2</span>)),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-37"><a href="salaire_belge_stat_desc.html#cb85-37" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Le point d&#39;inflexion (si la distribution est normale) à -1 écart type prend la valeur:&quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">-</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-38"><a href="salaire_belge_stat_desc.html#cb85-38" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;Le point d&#39;inflexion (si la distribution est normale) à +1 écart type prend la valeur:&quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">+</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>),<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-39"><a href="salaire_belge_stat_desc.html#cb85-39" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_1_inflex,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>,<span class="st">&quot; des valeurs se situent entre -1 et +1 écart types de la moyenne.&quot;</span>, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-40"><a href="salaire_belge_stat_desc.html#cb85-40" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_inflex_bas<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>,<span class="st">&quot; des valeurs se situent en dessous de -1 écart types de la moyenne.&quot;</span>,<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-41"><a href="salaire_belge_stat_desc.html#cb85-41" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_inflex_haut<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>,<span class="st">&quot; des valeurs se situent au-dessus de 1 écart types de la moyenne.&quot;</span>,<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-42"><a href="salaire_belge_stat_desc.html#cb85-42" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;-1,96 écarts types prend la valeur:&quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-43"><a href="salaire_belge_stat_desc.html#cb85-43" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;+1,96 écarts types prend la valeur:&quot;</span>, <span class="fu">round</span>(<span class="fu">mean</span>(x1, <span class="at">na.rm=</span>T)<span class="sc">+</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(x1, <span class="at">na.rm=</span>T),<span class="dv">2</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-44"><a href="salaire_belge_stat_desc.html#cb85-44" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_1<span class="fl">.96</span>,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>, <span class="st">&quot; des valeurs se situent entre -1,96 et +1,96 écart types de la moyenne.&quot;</span>, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-45"><a href="salaire_belge_stat_desc.html#cb85-45" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_bas<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>,<span class="st">&quot; des valeurs se situent en dessous de -1,96 écart types de la moyenne.&quot;</span>,<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>,</span>
<span id="cb85-46"><a href="salaire_belge_stat_desc.html#cb85-46" aria-hidden="true" tabindex="-1"></a>                <span class="fu">round</span>(pourcent_haut<span class="sc">*</span><span class="dv">100</span>,<span class="dv">2</span>),<span class="st">&quot;%&quot;</span>, <span class="st">&quot; des valeurs se situent au-dessus de 1,96 écart types de la moyenne.&quot;</span>)</span>
<span id="cb85-47"><a href="salaire_belge_stat_desc.html#cb85-47" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb85-48"><a href="salaire_belge_stat_desc.html#cb85-48" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Une fois que vous avez exécuté le code ci-dessus, la fonction <em>nonantecinq()</em> apparaîtra dans l’<a href="Priseenmain.html#objets_envir">environnement global</a> de R. Si vous fermer R et que vous n’enregistrez pas cet <a href="Priseenmain.html#objets_envir">environnement global</a>, vous devrez récréer la fonction <em>nonantecinq()</em> avec le code ci-dessus. Lorsque la fonction <em>nonantecinq()</em> est définie, vous pouvez la lancer comme toutes les fonctions de R de base ou des <em>packages</em>. Vous indiquez simplement le nom de la fonction avec les parenthèses dans lesquelles vous ajoutez, le cas échéant le ou les arguments. La fonction <em>nonantecinq()</em> ne prend qu’un seul argument qui doit être un vecteur numérique (une variable contenant des nombres). Ici, nous voulons vérifier le salaire des Belges (<em>grspnum</em>):</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="salaire_belge_stat_desc.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nonantecinq</span>(ESS9_BE_fulltime<span class="sc">$</span>grspnum)</span></code></pre></div>
<pre><code>##  Moyenne= 3365.44 
##  Écart type= 1673.51 
##  Médiane= 2986 
##  Mode (si multiples, le plus faible)= 3000 
##  Le point d&#39;inflexion (si la distribution est normale) à -1 écart type prend la valeur: 1691.93 
##  Le point d&#39;inflexion (si la distribution est normale) à +1 écart type prend la valeur: 5038.96 
##  85.36 %  des valeurs se situent entre -1 et +1 écart types de la moyenne. 
##  5.51 %  des valeurs se situent en dessous de -1 écart types de la moyenne. 
##  9.13 %  des valeurs se situent au-dessus de 1 écart types de la moyenne. 
##  -1,96 écarts types prend la valeur: 85.35 
##  +1,96 écarts types prend la valeur: 6645.53 
##  96.39 %  des valeurs se situent entre -1,96 et +1,96 écart types de la moyenne. 
##  0 %  des valeurs se situent en dessous de -1,96 écart types de la moyenne. 
##  3.61 %  des valeurs se situent au-dessus de 1,96 écart types de la moyenne.</code></pre>
<p>On voit donc également de manière “objective” que la variable salaire (<em>grspnum</em>) n’est absolument pas normale:</p>
<ul>
<li>La distribution n’est pas symétrique: <span class="math inline">\(5,51\%\)</span> des valeurs se situent en dessous de -1 écart types de la moyenne, tandis que <span class="math inline">\(9,13\%\)</span> des valeurs se situent au-dessus de 1 écart types de la moyenne.</li>
<li>La moyenne, la médiane et le mode sont différents. En particulier, la moyenne est plus élevée que le mode et la médiane.</li>
<li><span class="math inline">\(\approx85\%\)</span> des observations se trouvent entre -1 et +1 écart type (contre <span class="math inline">\(68\%\)</span> pour une distribution normale)</li>
<li><span class="math inline">\(0\%\)</span> des observations se trouvent en dessous de <span class="math inline">\(1,96\)</span> écart types (contre <span class="math inline">\(2,5\%\)</span> pour une distribution normale)</li>
<li><span class="math inline">\(3,6\%\)</span> des observations se trouvent au-dessus de <span class="math inline">\(1,96\)</span> écart types (contre <span class="math inline">\(2,5\%\)</span> pour une distribution normale)</li>
</ul>
</div>
<div id="trans_log_grspnum" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Distribution normale et transformation logarithmique<a href="salaire_belge_stat_desc.html#trans_log_grspnum" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La distribution de la variable des salaires (<em>grspnum</em>) est très éloignée d’une distribution normale. Quelques observations très élevées “tirent” la moyenne vers le haut. Cela est habituel pour les variables de type salaire ou patrimoine. Cependant, l’on peut souvent transformer ces variables de manière à les rapprocher d’une distribution normale. Une transformation très usitée pour cela est la transformation logarithmique (on prend souvent le <a href="https://fr.wikipedia.org/wiki/Logarithme_naturel">logarithme népérien</a>). Cela a pour effet de davantage espacer les valeurs faibles tout en réduisant les espaces entre les valeurs élevées. Nous vous illustrons cela graphiquement à l’aide une suite <span class="math inline">\(B\)</span> allant de <span class="math inline">\(1\)</span> à <span class="math inline">\(1000\)</span>:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="salaire_belge_stat_desc.html#cb88-1" aria-hidden="true" tabindex="-1"></a>suite_B<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> <span class="co"># Créons vecteur de 1 à 1000</span></span>
<span id="cb88-2"><a href="salaire_belge_stat_desc.html#cb88-2" aria-hidden="true" tabindex="-1"></a>log_suite_B<span class="ot">&lt;-</span><span class="fu">log</span>(suite_B) <span class="co"># Vecteur du logarithme de la suite B</span></span>
<span id="cb88-3"><a href="salaire_belge_stat_desc.html#cb88-3" aria-hidden="true" tabindex="-1"></a>suite_B_matrix<span class="ot">&lt;-</span><span class="fu">cbind</span>(suite_B,log_suite_B) <span class="co"># Nous créons une matrice avec les deux vecteurs</span></span>
<span id="cb88-4"><a href="salaire_belge_stat_desc.html#cb88-4" aria-hidden="true" tabindex="-1"></a>suite_B_df<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(suite_B_matrix) <span class="co"># Nous la transformons en base de données (dataframe)</span></span>
<span id="cb88-5"><a href="salaire_belge_stat_desc.html#cb88-5" aria-hidden="true" tabindex="-1"></a>suite_B_df <span class="sc">%&gt;%</span> <span class="co"># nous utilisions une &quot;pipe&quot;</span></span>
<span id="cb88-6"><a href="salaire_belge_stat_desc.html#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>suite_B,<span class="at">y=</span>log_suite_B)) <span class="sc">+</span></span>
<span id="cb88-7"><a href="salaire_belge_stat_desc.html#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Suite B&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-8"><a href="salaire_belge_stat_desc.html#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Logarithme népérien de la suite B&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-9"><a href="salaire_belge_stat_desc.html#cb88-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;ggplot2: Suite B et transformation logarithmique&quot;</span>)</span>
<span id="cb88-10"><a href="salaire_belge_stat_desc.html#cb88-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-11"><a href="salaire_belge_stat_desc.html#cb88-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(suite_B_df<span class="sc">$</span>suite_B, suite_B_df<span class="sc">$</span>log_suite_B, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>,</span>
<span id="cb88-12"><a href="salaire_belge_stat_desc.html#cb88-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">&quot;Base R: Suite B et transformation logarithmique&quot;</span>,</span>
<span id="cb88-13"><a href="salaire_belge_stat_desc.html#cb88-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Suite B&quot;</span>,</span>
<span id="cb88-14"><a href="salaire_belge_stat_desc.html#cb88-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Logarithme népérien de la suite B&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-59-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-59-2.png" width="50%" /></p>
<p>En abscisse, l’on voit la suite <span class="math inline">\(B\)</span> (l’objet <em>suite_B</em>) allant de 1 à 1000. En ordonné, nous avons cette même suite <span class="math inline">\(B\)</span> transformée de manière logarithmique. L’on voit, très clairement que la courbe augmente fortement lors de faibles valeurs puis s’aplanit. Cela correspond à l’augmentation de l’espacement des valeurs faibles et au rapprochement des grandes valeurs.</p>
<p>Nous allons donc appliquer cette transformation à la variable <em>grspnum</em> reprenant les salaires. Pour effectuer cette transformation, nous utilisons la fonction <a href="https://dplyr.tidyverse.org/reference/mutate.html"><em>mutate()</em></a> du <em>package</em> <a href="https://dplyr.tidyverse.org/"><em>dplyr</em></a>: celle-ci permet de créer de nouvelles variables dans une base de données. Cette fonction s’utilise de la manière suivante: vous indiquez comme premier argument, la base de donnés dans laquelle vous souhaitez ajouter une variable. Le deuxième argument correspond au nom de cette nouvelle variable suivie du signe <span class="math inline">\(=\)</span> et de la/des valeur(s) que doit prendre cette nouvelle variable. L’on peut ainsi indiquer que cette nouvelle variable doit correspondre au <em>logarithme népérien</em> de la variable <em>grspnum</em>. Le logarithme népérien se calcule avec la fonction <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/log"><em>log()</em></a>:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="salaire_belge_stat_desc.html#cb89-1" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ESS9_BE_fulltime,<span class="at">log_grspnum=</span><span class="fu">log</span>(grspnum))</span></code></pre></div>
<p>Regardons, dans quelle mesure la distribution a changée et si l’on s’est rapproché d’une distribution normale. Vérifions à l’aide d’un histogramme et d’un <em>boxplot</em> :</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="salaire_belge_stat_desc.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec R de base:</span></span>
<span id="cb90-2"><a href="salaire_belge_stat_desc.html#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="salaire_belge_stat_desc.html#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum,</span>
<span id="cb90-4"><a href="salaire_belge_stat_desc.html#cb90-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb90-5"><a href="salaire_belge_stat_desc.html#cb90-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">xlab =</span> <span class="st">&quot;Logarithme du salaire des Belges&quot;</span>, <span class="co"># Libellé de l&#39;abscisse.</span></span>
<span id="cb90-6"><a href="salaire_belge_stat_desc.html#cb90-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histogramme: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="co"># Titre du graphique</span></span>
<span id="cb90-7"><a href="salaire_belge_stat_desc.html#cb90-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-8"><a href="salaire_belge_stat_desc.html#cb90-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec ggplot2:</span></span>
<span id="cb90-9"><a href="salaire_belge_stat_desc.html#cb90-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-10"><a href="salaire_belge_stat_desc.html#cb90-10" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>log_grspnum)) <span class="sc">+</span> </span>
<span id="cb90-11"><a href="salaire_belge_stat_desc.html#cb90-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb90-12"><a href="salaire_belge_stat_desc.html#cb90-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramme: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="sc">+</span></span>
<span id="cb90-13"><a href="salaire_belge_stat_desc.html#cb90-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Logarithme du salaire des Belges&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-61-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-61-2.png" width="50%" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="salaire_belge_stat_desc.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec R de base:</span></span>
<span id="cb91-2"><a href="salaire_belge_stat_desc.html#cb91-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-3"><a href="salaire_belge_stat_desc.html#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum,</span>
<span id="cb91-4"><a href="salaire_belge_stat_desc.html#cb91-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">xlab =</span> <span class="st">&quot;Logarithme du salaire des Belges&quot;</span>, <span class="co"># Libellé de l&#39;abscisse.</span></span>
<span id="cb91-5"><a href="salaire_belge_stat_desc.html#cb91-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histogramme: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="co"># Titre du graphique</span></span>
<span id="cb91-6"><a href="salaire_belge_stat_desc.html#cb91-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-7"><a href="salaire_belge_stat_desc.html#cb91-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec ggplot2:</span></span>
<span id="cb91-8"><a href="salaire_belge_stat_desc.html#cb91-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-9"><a href="salaire_belge_stat_desc.html#cb91-9" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>log_grspnum)) <span class="sc">+</span> </span>
<span id="cb91-10"><a href="salaire_belge_stat_desc.html#cb91-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb91-11"><a href="salaire_belge_stat_desc.html#cb91-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Boxplot: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="sc">+</span></span>
<span id="cb91-12"><a href="salaire_belge_stat_desc.html#cb91-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Logarithme du salaire des Belges&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-62-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-62-2.png" width="50%" /></p>
<p>La distribution est sensiblement moins étirée. Cela ressemble plus à une distribution normale. Comparons l’histogramme avec une courbe de densité d’une distribution normale:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="salaire_belge_stat_desc.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec R de base:</span></span>
<span id="cb92-2"><a href="salaire_belge_stat_desc.html#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="salaire_belge_stat_desc.html#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plotNormalHistogram</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum,</span>
<span id="cb92-4"><a href="salaire_belge_stat_desc.html#cb92-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb92-5"><a href="salaire_belge_stat_desc.html#cb92-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">xlab =</span> <span class="st">&quot;Logarithme du salaire des Belges&quot;</span>, <span class="co"># Libellé de l&#39;abscisse.</span></span>
<span id="cb92-6"><a href="salaire_belge_stat_desc.html#cb92-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Histogramme: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="co"># Titre du graphique</span></span>
<span id="cb92-7"><a href="salaire_belge_stat_desc.html#cb92-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-8"><a href="salaire_belge_stat_desc.html#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Avec ggplot2:</span></span>
<span id="cb92-9"><a href="salaire_belge_stat_desc.html#cb92-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-10"><a href="salaire_belge_stat_desc.html#cb92-10" aria-hidden="true" tabindex="-1"></a>ESS9_BE_fulltime <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>log_grspnum)) <span class="sc">+</span> </span>
<span id="cb92-11"><a href="salaire_belge_stat_desc.html#cb92-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span>..density..), <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb92-12"><a href="salaire_belge_stat_desc.html#cb92-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm,</span>
<span id="cb92-13"><a href="salaire_belge_stat_desc.html#cb92-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),</span>
<span id="cb92-14"><a href="salaire_belge_stat_desc.html#cb92-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">sd =</span> <span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum)),</span>
<span id="cb92-15"><a href="salaire_belge_stat_desc.html#cb92-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="fl">1.25</span>) <span class="sc">+</span></span>
<span id="cb92-16"><a href="salaire_belge_stat_desc.html#cb92-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramme: Logarithme du salaire des Belges en 2018&quot;</span>) <span class="sc">+</span></span>
<span id="cb92-17"><a href="salaire_belge_stat_desc.html#cb92-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Logarithme du salaire des Belges&quot;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-63-1.png" width="50%" /><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-63-2.png" width="50%" /></p>
<p>Vérifions cela à l’aide de la fonction <em>nonantecinq</em>:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="salaire_belge_stat_desc.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nonantecinq</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum)</span></code></pre></div>
<pre><code>##  Moyenne= 8.03 
##  Écart type= 0.42 
##  Médiane= 8 
##  Mode (si multiples, le plus faible)= 8.01 
##  Le point d&#39;inflexion (si la distribution est normale) à -1 écart type prend la valeur: 7.61 
##  Le point d&#39;inflexion (si la distribution est normale) à +1 écart type prend la valeur: 8.44 
##  67.3 %  des valeurs se situent entre -1 et +1 écart types de la moyenne. 
##  15.78 %  des valeurs se situent en dessous de -1 écart types de la moyenne. 
##  16.92 %  des valeurs se situent au-dessus de 1 écart types de la moyenne. 
##  -1,96 écarts types prend la valeur: 7.21 
##  +1,96 écarts types prend la valeur: 8.84 
##  94.68 %  des valeurs se situent entre -1,96 et +1,96 écart types de la moyenne. 
##  1.71 %  des valeurs se situent en dessous de -1,96 écart types de la moyenne. 
##  3.61 %  des valeurs se situent au-dessus de 1,96 écart types de la moyenne.</code></pre>
<p>Les données numériques sont tout autant instructives que le diagnostic visuel:</p>
<ul>
<li>Le mode, la médiane et la moyenne sont tous très proches de <span class="math inline">\(8\)</span> (et donc presque identiques).</li>
<li><span class="math inline">\(67\%\)</span> des observations se trouvent entre <span class="math inline">\(-1\)</span> et <span class="math inline">\(+1\)</span> écart type (contre <span class="math inline">\(\approx68\%\)</span> d’une distribution normale).</li>
<li><span class="math inline">\(\approx95\%\)</span> des observations se trouvent entre <span class="math inline">\(-1,96\)</span> et <span class="math inline">\(+1,96\)</span> écart types (comme pour une distribution normale).</li>
<li><span class="math inline">\(2\%\)</span> des observations se trouvent en dessous de <span class="math inline">\(-1,96\)</span> écart types et <span class="math inline">\(4%\)</span> se trouvent au-dessus de <span class="math inline">\(+1,96\)</span> écart types (contre <span class="math inline">\(2,5\%\)</span> en dessous et au-dessus dans une distribution normale).</li>
</ul>
<p>Empiriquement, nous ne sommes pas face à une distribution tout à fait normale, mais nous en sommes très proches. Cela d’autant plus que le salaire (<em>grspnum</em>, d’où <em>log_grspnum</em>) est une variable continue, que la réponse est une déclaration spontanée (les sondés auront tendance à donner des chiffres “ronds”)<a href="#fn34" class="footnote-ref" id="fnref34"><sup>34</sup></a> et que l’échantillon est assez grand (<span class="math inline">\(n=526\)</span>). Il y a donc une très forte probabilité que la variable sous-jacente dans la population suive une distribution normale. L’on peut donc traiter la variable salaire transformée (<em>log_grspnum</em>) comme une distribution normale. Cela nous permet à calculer des probabilités comme nous allons le voir dans le <a href="salaire_belge_stat_desc.html#distribution_normale_proba">prochain chapitre</a>.</p>
</div>
<div id="distribution_normale_proba" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Distribution normale et probabilités<a href="salaire_belge_stat_desc.html#distribution_normale_proba" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La distribution normale a un certain nombre de propriétés très intéressantes. L’une d’entre elles et que lorsqu’on connait la moyenne et la variance/l’écart type (ou qu’on l’estime) d’une distribution normale, l’on peut facilement connaître la probabilité d’obtenir une valeur dans un certain intervalle. On se sert de cette propriété dans la statistique inférentielle (qui vise à apporter des connaissances sur la population et pas seulement sur l’échantillon), car les moyennes d’échantillons d’assez grande taille (<span class="math inline">\(n&gt;30\)</span>) tirés d’une même population suivent une loi normale (même si la variable étudiée ne suit pas une distribution normale). Cela permet de calculer des intervalles de confiance et le risque de faux positifs (<em>p-valeur</em>) et de tirer des conclusions sur la population dont est issu l’échantillon<a href="#fn35" class="footnote-ref" id="fnref35"><sup>35</sup></a>.</p>
</div>
<div id="connaître-la-probabilité-des-salaires" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Connaître la probabilité des salaires<a href="salaire_belge_stat_desc.html#connaître-la-probabilité-des-salaires" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La variable <em>log_grspnum</em> que l’on a créée dans le <a href="salaire_belge_stat_desc.html#trans_log_grspnum">chapitre précédent</a> reprend la transformation logarithmique du revenu mensuel des Belges travaillant à temps plein (<span class="math inline">\(&gt;34\)</span> heures de travail), sans des valeurs aberrantes (trop faibles pour un travail à temps plein) et des revenus dépassant les <span class="math inline">\(15.000€\)</span>. Cette variable <em>log_grspnum</em> peut être considérée comme suivant une distribution normale. Par conséquent, l’on peut facilement déterminer la probabilité qu’un Belge travaillant à temps plein touche un salaire dans un certain intervalle. On peut, par exemple, déterminer quelle est la probabilité de bénéficier d’un revenu supérieur à <span class="math inline">\(3000€\)</span>, inférieur à <span class="math inline">\(1000€\)</span> ou située entre <span class="math inline">\(1350€\)</span> et <span class="math inline">\(1400€\)</span>.</p>
<p>R permet de calculer cette probabilité de manière très simple à l’aide de la fonction <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Normal"><em>pnorm()</em></a>. Celle-ci permet de calculer la probabilité qu’une valeur se trouve dans un certain intervalle, en indiquant la valeur dont on veut connaitre la probabilité, la moyenne, l’écart type et si l’on cherche l’intervalle supérieur ou inférieur à la valeur recherchée. R permet, par ailleurs, de représenter graphiquement assez simples ces intervalles.</p>
<p>Notre exemple comporte une difficulté supplémentaire, car nous avons transformé le salaire avec le logarithme népérien. En effet, nous ne pouvons pas directement indiquer l’intervalle de revenu dont nous souhaitons connaître la probabilité. Il faut que nous transformions le salaire que nous voulons tester à l’aide du logarithme népérien<a href="#fn36" class="footnote-ref" id="fnref36"><sup>36</sup></a>. Vu que R permet d’imbriquer des fonctions, l’on peut assez facilement surmonter cette difficulté.</p>
<p>Si vous nous voulons connaitre la probabilité de bénéficier d’un revenu supérieur à <span class="math inline">\(2500€\)</span>, nous pouvons le faire ainsi:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="salaire_belge_stat_desc.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fu">log</span>(<span class="dv">2500</span>), <span class="co"># Le logarithme népérien de 2500</span></span>
<span id="cb95-2"><a href="salaire_belge_stat_desc.html#cb95-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb95-3"><a href="salaire_belge_stat_desc.html#cb95-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb95-4"><a href="salaire_belge_stat_desc.html#cb95-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> F <span class="co">#Nous voulons connaitre la probabilité que la valeur soit au-dessus de 2500</span></span>
<span id="cb95-5"><a href="salaire_belge_stat_desc.html#cb95-5" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div>
<pre><code>## [1] 0.6882183</code></pre>
<p>La probabilité de percevoir un salaire supérieur à <span class="math inline">\(2500€\)</span> est exprimé en probabilité: <span class="math inline">\(0,69\)</span>, ce qui correspond à <span class="math inline">\(69\%\)</span>.</p>
<!-- L'on peut représenter cet intervalle graphiquement: -->
<!-- ```{r eval=T} -->
<!-- plot(seq(6.5, -->
<!--      max(ESS9_BE_fulltime$log_grspnum), -->
<!--      by=0.001), -->
<!--   dnorm(seq(6.5, -->
<!--      max(ESS9_BE_fulltime$log_grspnum), by=0.001), -->
<!--      mean(ESS9_BE_fulltime$log_grspnum), -->
<!--      sd(ESS9_BE_fulltime$log_grspnum)), # Plot where y = values and x = index of the value in the vector -->
<!--      #xlim=c(6.5,max(ESS9_BE_fulltime$log_grspnum)), -->
<!--      #xaxt = "n", # Don't label the x-axis -->
<!--      type = "l", # Make it a line plot -->
<!--      main = paste("Distribution normale avec une moyenne de", -->
<!--                   round(mean(ESS9_BE_fulltime$log_grspnum),2), -->
<!--                   "et un écart type de", -->
<!--                   round(sd(ESS9_BE_fulltime$log_grspnum),2)), -->
<!--      xlab= "Log-€", -->
<!--      ylab="Densité")  -->
<!-- #Colorier la zone en dessous de la courbe: -->
<!-- polygon( -->
<!--     x=c(seq(log(2500), -->
<!--     max(ESS9_BE_fulltime$log_grspnum), -->
<!--     by=0.001), -->
<!--     rev(seq(log(2500), -->
<!--     max(ESS9_BE_fulltime$log_grspnum), -->
<!--     by=0.001))), -->
<!--     y=c(dnorm(seq(log(2500), -->
<!--     max(ESS9_BE_fulltime$log_grspnum), -->
<!--     by=0.001), -->
<!--     mean(ESS9_BE_fulltime$log_grspnum), -->
<!--      sd(ESS9_BE_fulltime$log_grspnum)), -->
<!--     rep(0,length(seq(log(2500), -->
<!--     max(ESS9_BE_fulltime$log_grspnum), -->
<!--     by=0.001)))), -->
<!--     col = "grey" -->
<!--     ) -->
<!-- ``` -->
<p>Si l’on voulons calculer la probabilité de percevoir un salaire inférieur à <span class="math inline">\(2500€\)</span>, l’on indique le code suivant:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="salaire_belge_stat_desc.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fu">log</span>(<span class="dv">2500</span>), <span class="co"># Le logarithme népérien de 2500</span></span>
<span id="cb97-2"><a href="salaire_belge_stat_desc.html#cb97-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb97-3"><a href="salaire_belge_stat_desc.html#cb97-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb97-4"><a href="salaire_belge_stat_desc.html#cb97-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> T <span class="co">#Nous voulons connaitre la probabilité que la valeur soit en dessous de 2500</span></span>
<span id="cb97-5"><a href="salaire_belge_stat_desc.html#cb97-5" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div>
<pre><code>## [1] 0.3117817</code></pre>
<p>La probabilité de percevoir un salaire inférieur à <span class="math inline">\(2500€\)</span> est donc de <span class="math inline">\(0,31\)</span> soit <span class="math inline">\(31\%\)</span>. Vous aurez noté que la probabilité cumulé de percevoir un salaire inférieur à <span class="math inline">\(2500€\)</span> et supérieur à <span class="math inline">\(2500€\)</span> est de <span class="math inline">\(1\)</span> (<span class="math inline">\(0,69+0,31=1\)</span>). L’on peut utiliser cela pour calculer la probabilité e percevoir un salaire dans un certain intervalle. Si l’on voulait connaître la probabilité de percevoir un salaire supérieur à <span class="math inline">\(2500€\)</span>,mais inférieur à <span class="math inline">\(2800€\)</span>, l’on calcule simplement:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="salaire_belge_stat_desc.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#La probabilité de bénéficier d&#39;un salaire inférieur à 2800 €</span></span>
<span id="cb99-2"><a href="salaire_belge_stat_desc.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="co">#On l&#39;appelle proba_inf_2800</span></span>
<span id="cb99-3"><a href="salaire_belge_stat_desc.html#cb99-3" aria-hidden="true" tabindex="-1"></a>proba_inf_2800<span class="ot">&lt;-</span><span class="fu">pnorm</span>(<span class="fu">log</span>(<span class="dv">2800</span>), <span class="co"># Le logarithme népérien de 2800</span></span>
<span id="cb99-4"><a href="salaire_belge_stat_desc.html#cb99-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb99-5"><a href="salaire_belge_stat_desc.html#cb99-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb99-6"><a href="salaire_belge_stat_desc.html#cb99-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> T <span class="co">#Nous voulons connaitre la probabilité que la valeur soit en dessous de 2800</span></span>
<span id="cb99-7"><a href="salaire_belge_stat_desc.html#cb99-7" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb99-8"><a href="salaire_belge_stat_desc.html#cb99-8" aria-hidden="true" tabindex="-1"></a>proba_inf_2800</span></code></pre></div>
<pre><code>## [1] 0.413685</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="salaire_belge_stat_desc.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#La probabilité de bénéficier d&#39;un salaire inférieur à 2500 €</span></span>
<span id="cb101-2"><a href="salaire_belge_stat_desc.html#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="co">#On l&#39;appelle proba_inf_2500</span></span>
<span id="cb101-3"><a href="salaire_belge_stat_desc.html#cb101-3" aria-hidden="true" tabindex="-1"></a>proba_inf_2500<span class="ot">&lt;-</span><span class="fu">pnorm</span>(<span class="fu">log</span>(<span class="dv">2500</span>), <span class="co"># Le logarithme népérien de 2500</span></span>
<span id="cb101-4"><a href="salaire_belge_stat_desc.html#cb101-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb101-5"><a href="salaire_belge_stat_desc.html#cb101-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb101-6"><a href="salaire_belge_stat_desc.html#cb101-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> T <span class="co">#Nous voulons connaitre la probabilité que la valeur soit en dessous de 2500</span></span>
<span id="cb101-7"><a href="salaire_belge_stat_desc.html#cb101-7" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb101-8"><a href="salaire_belge_stat_desc.html#cb101-8" aria-hidden="true" tabindex="-1"></a>proba_inf_2500</span></code></pre></div>
<pre><code>## [1] 0.3117817</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="salaire_belge_stat_desc.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co">#La différence entre la probabilité</span></span>
<span id="cb103-2"><a href="salaire_belge_stat_desc.html#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="co">#de bénéficier d&#39;un salaire supérieur à 2500€ (proba_inf_2500) et</span></span>
<span id="cb103-3"><a href="salaire_belge_stat_desc.html#cb103-3" aria-hidden="true" tabindex="-1"></a><span class="co">#la probabilité de bénéficier d&#39;un salaire inférieur à 2800 € (proba_inf_2800):</span></span>
<span id="cb103-4"><a href="salaire_belge_stat_desc.html#cb103-4" aria-hidden="true" tabindex="-1"></a>proba_combi_2500_2800<span class="ot">&lt;-</span>proba_inf_2800<span class="sc">-</span>proba_inf_2500</span>
<span id="cb103-5"><a href="salaire_belge_stat_desc.html#cb103-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-6"><a href="salaire_belge_stat_desc.html#cb103-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Cette différence donne:</span></span>
<span id="cb103-7"><a href="salaire_belge_stat_desc.html#cb103-7" aria-hidden="true" tabindex="-1"></a>proba_combi_2500_2800</span></code></pre></div>
<pre><code>## [1] 0.1019033</code></pre>
<p>La probabilité de bénéficier d’un salaire entre <span class="math inline">\(2500€\)</span> et <span class="math inline">\(2800€\)</span> est donc de <span class="math inline">\(0,1\)</span>, soit <span class="math inline">\(10\%\)</span>. En effet, la probabilité de bénéficier d’un salaire de moins de <span class="math inline">\(2800€\)</span> est de <span class="math inline">\(0,41\)</span> (<span class="math inline">\(41\%\)</span>). La probabilité de bénéficier d’un salaire de moins de <span class="math inline">\(2500€\)</span> est de <span class="math inline">\(0,31\)</span> (<span class="math inline">\(31\%\)</span>). D’où, si l’on prend la différence entre les deux l’on trouve la probabilité de bénéficier d’un salaire entre <span class="math inline">\(2500€\)</span> et <span class="math inline">\(2800€\)</span> (<span class="math inline">\(0,41-0,31=0,1\)</span>).</p>
<p>L’on peut représenter cela de manière visuelle. Par simplicité, nous utilisions le code généré par l’interface graphique “<em>R Commander</em>” (<a href="https://cran.r-project.org/web/packages/Rcmdr/index.html"><em>Rcmdr</em></a>)<a href="#fn37" class="footnote-ref" id="fnref37"><sup>37</sup></a>. D’autres manière de représenter cela impliquent de combiner, voir d’imbriquer, des fonctions telles que <a href="https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/polygon">polygon()</a>/<a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon()</a>, <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Normal.html">dnorm()</a> et éventuellement <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/rev">rev()</a> et <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/rep">rep()</a> qui nous semble trop complliqués à expliquer dans ce syllabus. pour utiliser les fonctions issues du <em>package</em> <a href="https://cran.r-project.org/web/packages/Rcmdr/index.html"><em>Rcmdr</em></a>, lancez le ainsi:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="salaire_belge_stat_desc.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(Rcmdr)</span></code></pre></div>
<p>Ensuite, vous pouvez soit faire les manipulations dans “R Commander” ou utiliser le code dans le <em>R Script </em>. Si vous souhaiter utiliser le code dans le R Script, je vous conseille de fermer la fenêtre du “R Commander” pour que les graphiques générés n’apparaissent pas dans la fenêtre du “R Commander” pas à leur emplacment habituel:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="salaire_belge_stat_desc.html#cb106-1" aria-hidden="true" tabindex="-1"></a>.x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">6.661</span>, <span class="fl">9.395</span>, <span class="at">length.out=</span><span class="dv">1000</span>)  </span>
<span id="cb106-2"><a href="salaire_belge_stat_desc.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plotDistr</span>(.x,</span>
<span id="cb106-3"><a href="salaire_belge_stat_desc.html#cb106-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">dnorm</span>(.x,</span>
<span id="cb106-4"><a href="salaire_belge_stat_desc.html#cb106-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean=</span><span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),</span>
<span id="cb106-5"><a href="salaire_belge_stat_desc.html#cb106-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum)),</span>
<span id="cb106-6"><a href="salaire_belge_stat_desc.html#cb106-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">cdf=</span><span class="cn">FALSE</span>,</span>
<span id="cb106-7"><a href="salaire_belge_stat_desc.html#cb106-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">xlab=</span><span class="st">&quot;Revenu en log(€)&quot;</span>,</span>
<span id="cb106-8"><a href="salaire_belge_stat_desc.html#cb106-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">ylab=</span><span class="st">&quot;Densité&quot;</span>, </span>
<span id="cb106-9"><a href="salaire_belge_stat_desc.html#cb106-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="fu">paste</span>(<span class="st">&quot;Normal Distribution:  Mean=8.027993, Standard deviation=0.4155336&quot;</span>),</span>
<span id="cb106-10"><a href="salaire_belge_stat_desc.html#cb106-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">regions=</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="fu">log</span>(<span class="dv">2500</span>), <span class="fu">log</span>(<span class="dv">2800</span>))),</span>
<span id="cb106-11"><a href="salaire_belge_stat_desc.html#cb106-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;#BEBEBE&#39;</span>, <span class="st">&#39;#BEBEBE&#39;</span>),</span>
<span id="cb106-12"><a href="salaire_belge_stat_desc.html#cb106-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.pos=</span><span class="st">&#39;topright&#39;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>Grâce à ce graphique l’on voit visuellement où se situent les <span class="math inline">\(10\%\)</span> de probabilité de percevoir entre <span class="math inline">\(2500€\)</span> et <span class="math inline">\(2800€\)</span>.</p>
<p>L’on peut aussi calculer le montant à partir duquel l’on perçoit un revenu supérieur à 80% de la population et à partir duquel on appartient aux Belges percevant les 10% de revenus les plus faibles. Cela se calcule aisément avec la fonction <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Normal"><em>qnorm()</em></a>. L’on indique en tant que premier argument le pourcentage (de 0 à 1) qu’on souhaiterait connaitre, puis comme deuxième et troisième argument la moyenne et l’écart type. Par défaut, R vous retourne la probabilité de percevoir moins. Si vous voulez connaître la probabilité de percevoir plus, il faut spécifier un quatrième argument: “<em>lower.tail=F</em>”.</p>
<p>Calculons donc la probabilité de percevoir un revenu supérieur à 80% de la population:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="salaire_belge_stat_desc.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.8</span>, <span class="co"># 80%</span></span>
<span id="cb107-2"><a href="salaire_belge_stat_desc.html#cb107-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb107-3"><a href="salaire_belge_stat_desc.html#cb107-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb107-4"><a href="salaire_belge_stat_desc.html#cb107-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> F <span class="co">#Nous voulons connaitre la probabilité que la valeur soit au-dessus de 0.8 (80%)</span></span>
<span id="cb107-5"><a href="salaire_belge_stat_desc.html#cb107-5" aria-hidden="true" tabindex="-1"></a>      )</span></code></pre></div>
<pre><code>## [1] 7.678271</code></pre>
<p>Le montant à partir duquel l’on perçoit plus que 80% de la population est de <span class="math inline">\(7.68\)</span>. Ce montant est difficilement interprétable. En effet, il s’agit du logarithme népérien du revenu. Il faut donc transformer cette valeur. On passe du logarithme népérien à la valeur d’origine en appliquant une transformation exponentielle à la valeur. Pour cela, l’on peut utiliser la fonction <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/log"><em>exp()</em></a>:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="salaire_belge_stat_desc.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#On calcule la valeur exacte et l&#39;appelle plus_80_pc</span></span>
<span id="cb109-2"><a href="salaire_belge_stat_desc.html#cb109-2" aria-hidden="true" tabindex="-1"></a>plus_80_pc<span class="ot">&lt;-</span><span class="fu">qnorm</span>(<span class="fl">0.8</span>, <span class="co"># 80%</span></span>
<span id="cb109-3"><a href="salaire_belge_stat_desc.html#cb109-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb109-4"><a href="salaire_belge_stat_desc.html#cb109-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb109-5"><a href="salaire_belge_stat_desc.html#cb109-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> T <span class="co">#Nous voulons connaitre la probabilité que la valeur soit en dessous de 0.8 (80%)</span></span>
<span id="cb109-6"><a href="salaire_belge_stat_desc.html#cb109-6" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb109-7"><a href="salaire_belge_stat_desc.html#cb109-7" aria-hidden="true" tabindex="-1"></a><span class="co">#On transforme cette valeur en euro:</span></span>
<span id="cb109-8"><a href="salaire_belge_stat_desc.html#cb109-8" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(plus_80_pc)</span></code></pre></div>
<pre><code>## [1] 4349.057</code></pre>
<p>Il en découle que l’on doit percevoir plus de <span class="math inline">\(4349,06€\)</span> par mois pour gagner plus de 80% des personnes travaillant à temps plein en Belgique. L’on peut représenter cela graphiquement:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="salaire_belge_stat_desc.html#cb111-1" aria-hidden="true" tabindex="-1"></a>.x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">6.661</span>, <span class="fl">9.395</span>, <span class="at">length.out=</span><span class="dv">1000</span>)  </span>
<span id="cb111-2"><a href="salaire_belge_stat_desc.html#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plotDistr</span>(.x,</span>
<span id="cb111-3"><a href="salaire_belge_stat_desc.html#cb111-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">dnorm</span>(.x,</span>
<span id="cb111-4"><a href="salaire_belge_stat_desc.html#cb111-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean=</span><span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),</span>
<span id="cb111-5"><a href="salaire_belge_stat_desc.html#cb111-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum)),</span>
<span id="cb111-6"><a href="salaire_belge_stat_desc.html#cb111-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">cdf=</span><span class="cn">FALSE</span>,</span>
<span id="cb111-7"><a href="salaire_belge_stat_desc.html#cb111-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">xlab=</span><span class="st">&quot;Revenu en log(€)&quot;</span>,</span>
<span id="cb111-8"><a href="salaire_belge_stat_desc.html#cb111-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">ylab=</span><span class="st">&quot;Densité&quot;</span>, </span>
<span id="cb111-9"><a href="salaire_belge_stat_desc.html#cb111-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="fu">paste</span>(<span class="st">&quot;Normal Distribution:  Mean=8.027993, Standard deviation=0.4155336&quot;</span>),</span>
<span id="cb111-10"><a href="salaire_belge_stat_desc.html#cb111-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">regions=</span><span class="fu">list</span>(<span class="fu">c</span>(plus_80_pc, <span class="dv">15</span>)),</span>
<span id="cb111-11"><a href="salaire_belge_stat_desc.html#cb111-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;#BEBEBE&#39;</span>, <span class="st">&#39;#BEBEBE&#39;</span>),</span>
<span id="cb111-12"><a href="salaire_belge_stat_desc.html#cb111-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.pos=</span><span class="st">&#39;topright&#39;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>Si l’on veut déterminer à partir de quelle somme l’on appartient aux 10% des Belges travaillant à temps plein percevant le moins de revenu, il faut calculer ainsi:</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="salaire_belge_stat_desc.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co">#On calcule la valeur exacte et l&#39;appelle moins_10_pc</span></span>
<span id="cb112-2"><a href="salaire_belge_stat_desc.html#cb112-2" aria-hidden="true" tabindex="-1"></a>moins_10_pc<span class="ot">&lt;-</span><span class="fu">qnorm</span>(<span class="fl">0.1</span>, <span class="co"># 80%</span></span>
<span id="cb112-3"><a href="salaire_belge_stat_desc.html#cb112-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum), <span class="co">#la moyenne de la variable log_grspnum</span></span>
<span id="cb112-4"><a href="salaire_belge_stat_desc.html#cb112-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),<span class="co">#l&#39;écart type de la variable log_grspnum</span></span>
<span id="cb112-5"><a href="salaire_belge_stat_desc.html#cb112-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">lower.tail =</span> T <span class="co">#Nous voulons connaitre la probabilité que la valeur soit en dessous de 0.1 (10%)</span></span>
<span id="cb112-6"><a href="salaire_belge_stat_desc.html#cb112-6" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb112-7"><a href="salaire_belge_stat_desc.html#cb112-7" aria-hidden="true" tabindex="-1"></a>moins_10_pc</span></code></pre></div>
<pre><code>## [1] 7.495465</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="salaire_belge_stat_desc.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co">#On transforme cette valeur en euro:</span></span>
<span id="cb114-2"><a href="salaire_belge_stat_desc.html#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(moins_10_pc)</span></code></pre></div>
<pre><code>## [1] 1799.861</code></pre>
<p>Il faut donc percevoir moins de <span class="math inline">\(1799,86€\)</span> pour appartenir au 10% des Belges travaillant à temps plein percevant les revenus les plus faibles. L’on peut également représenter cela graphiquement:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="salaire_belge_stat_desc.html#cb116-1" aria-hidden="true" tabindex="-1"></a>.x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">6.661</span>, <span class="fl">9.395</span>, <span class="at">length.out=</span><span class="dv">1000</span>)  </span>
<span id="cb116-2"><a href="salaire_belge_stat_desc.html#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plotDistr</span>(.x,</span>
<span id="cb116-3"><a href="salaire_belge_stat_desc.html#cb116-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">dnorm</span>(.x,</span>
<span id="cb116-4"><a href="salaire_belge_stat_desc.html#cb116-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mean=</span><span class="fu">mean</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum),</span>
<span id="cb116-5"><a href="salaire_belge_stat_desc.html#cb116-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sd=</span><span class="fu">sd</span>(ESS9_BE_fulltime<span class="sc">$</span>log_grspnum)),</span>
<span id="cb116-6"><a href="salaire_belge_stat_desc.html#cb116-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">cdf=</span><span class="cn">FALSE</span>,</span>
<span id="cb116-7"><a href="salaire_belge_stat_desc.html#cb116-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">xlab=</span><span class="st">&quot;Revenu en log(€)&quot;</span>,</span>
<span id="cb116-8"><a href="salaire_belge_stat_desc.html#cb116-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">ylab=</span><span class="st">&quot;Densité&quot;</span>, </span>
<span id="cb116-9"><a href="salaire_belge_stat_desc.html#cb116-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">main=</span><span class="fu">paste</span>(<span class="st">&quot;Normal Distribution:  Mean=8.027993, Standard deviation=0.4155336&quot;</span>),</span>
<span id="cb116-10"><a href="salaire_belge_stat_desc.html#cb116-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">regions=</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, moins_10_pc)),</span>
<span id="cb116-11"><a href="salaire_belge_stat_desc.html#cb116-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">col=</span><span class="fu">c</span>(<span class="st">&#39;#BEBEBE&#39;</span>, <span class="st">&#39;#BEBEBE&#39;</span>),</span>
<span id="cb116-12"><a href="salaire_belge_stat_desc.html#cb116-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.pos=</span><span class="st">&#39;topright&#39;</span>)</span></code></pre></div>
<p><img src="intro_R_sciences_sociales_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>On peut également faire des calculs similaires pour d’autres types de distributions que la distribution <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Normal">normale</a>. Vous trouverez ici une liste non exhaustive des distributions pour lesquelles R propose des fonctions:</p>
<ul>
<li>la distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Binomial.html">binomiale</a></li>
<li>la distribution du <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Chisquare">khi-deux</a></li>
<li>la distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Exponential.html">exponentielle</a></li>
<li>la distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Fdist.html">F (loi de Fisher-Snedecor)</a></li>
<li>la distribution <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Logistic">logistique</a></li>
<li>la distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Lognormal.html">log-normale</a></li>
<li>La distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Poisson.html">poisson</a></li>
<li>La distribution <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/TDist.html">t de <em>Student</em></a></li>
<li>La distribution <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Uniform">uniforme</a></li>
</ul>
<!-- ## Interface graphique: *R Commander* (Rcmdr) -->
<!-- # Applications -->
<!-- Some _significant_ applications are demonstrated in this chapter. -->
<!-- ## Example one -->
<!-- ## Example two -->
<!-- We describe our methods in this chapter. -->
<!-- Math can be added in body using usual syntax like this  -->
<!-- ## math example -->
<!-- $p$ is unknown but expected to be around 1/3. Standard error will be approximated -->
<!-- $$ -->
<!-- SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027 -->
<!-- $$ -->
<!-- You can also use math in footnotes like this^[where we mention $p = \frac{a}{b}$]. -->
<!-- We will approximate standard error to 0.027[^longnote] -->
<!-- [^longnote]: $p$ is unknown but expected to be around 1/3. Standard error will be approximated -->
<!--     $$ -->
<!--     SE = \sqrt(\frac{p(1-p)}{n}) \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027 -->
<!--     $$ -->

</div>
</div>










































<div class="footnotes">
<hr />
<ol start="28">
<li id="fn28"><p>Nous définissions qu’il y a 50 barres dans l’histogramme: “breaks = 50” comme second argument de la fonction <a href="https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist"><em>hist()</em></a> et <a href="https://www.rdocumentation.org/packages/rcompanion/versions/2.4.21/topics/plotNormalHistogram"><em>plotNormalHistogram</em></a>.<a href="salaire_belge_stat_desc.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>Nous définissons qu’il y a 50 barres dans l’histogramme: “bins=50” comme second argument de la fonction <a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html"><em>geom_histogram</em></a>.<a href="salaire_belge_stat_desc.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Si vous comparer le code du <em>boxplot</em> à l’histogramme avec <a href="https://ggplot2.tidyverse.org/"><em>ggplot2</em></a>, vous remarquerez, que seule la deuxième partie de la commande a changée. Cette similarité du code est un grand avantage du <em>package</em> <a href="https://ggplot2.tidyverse.org/"><em>ggplot2</em></a>. Nous reviendrons plus tard sur la syntaxe et l’utilisation de <a href="https://ggplot2.tidyverse.org/"><em>ggplot2</em></a>.<a href="salaire_belge_stat_desc.html#fnref30" class="footnote-back">↩︎</a></p></li>
<li id="fn31"><p>Il est certainement possible qu’il y ait des cas très spécifiques où cela puisse se produire. Mais nous excluons ces cas de nos analyses.<a href="salaire_belge_stat_desc.html#fnref31" class="footnote-back">↩︎</a></p></li>
<li id="fn32"><p>Il faudrait analyser plus en détail ces cas anormaux: peut-être que les personnes concernées exercent des professions en tant qu’indépendants et s’estiment “de garde” en permanence.<a href="salaire_belge_stat_desc.html#fnref32" class="footnote-back">↩︎</a></p></li>
<li id="fn33"><p>Vu qu’il ne s’agit pas d’une introduction à la programmation avec R, nous ne nous attardons pas sur l’écriture de fonctions dans R. Nous renvoyons à l’ouvrage <a href="https://cran.r-project.org/doc/contrib/Goulet_introduction_programmation_R.pdf">“Introduction à la programmation en R”</a> de Vincent Goulet et plus particulièrement au chapitre 5: “Fonctions définies par l’usager”.<a href="salaire_belge_stat_desc.html#fnref33" class="footnote-back">↩︎</a></p></li>
<li id="fn34"><p>Si l’on avait accès aux données de revenus comme l’a l’administration fiscale (en Belgique: <a href="https://finances.belgium.be/fr">SPF Finances</a>) et les organismes de la sécurité sociale (en Belgique notamment par le biais de la <a href="https://www.ksz-bcss.fgov.be/fr">BCSS</a>), la distribution serait vraisemblablement encore plus proche de la distribution normale.<a href="salaire_belge_stat_desc.html#fnref34" class="footnote-back">↩︎</a></p></li>
<li id="fn35"><p>Pour les concepts d’échantillon et de population, d’intervalles de confiance, de <em>p-valeur</em> nous renvoyons aux ouvrages d’introduction aux statistiques. Notons que contrairement à des formulations que l’on peut trouver ça et là, les “vraies” valeurs dans la population sont et restent toujours inconnues. Les estimations que l’on peut obtenir par des procédés mathématiques ne permettent pas de connaître cette “vraie” valeur. L’on peut simplement connaître la probabilité d’obtenir une valeur dans l’intervalle calculée si l’on prend un nouvel échantillon dans la population.<a href="salaire_belge_stat_desc.html#fnref35" class="footnote-back">↩︎</a></p></li>
<li id="fn36"><p>Attention: Si nous travaillons avec des données qui ne sont pas transformées, il n’y pas besoin de faire une telle transformation!<a href="salaire_belge_stat_desc.html#fnref36" class="footnote-back">↩︎</a></p></li>
<li id="fn37"><p>Ce syllabus ne s’attarde pas sur le fonctionnement de cet interface graphique. Vous trouverez des explications en ligne, notamment: <a href="https://lms.fun-mooc.fr/c4x/UPSUD/42001S02/asset/introRcmdr.html">https://lms.fun-mooc.fr/c4x/UPSUD/42001S02/asset/introRcmdr.html</a><a href="salaire_belge_stat_desc.html#fnref37" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="charge_code_filtrer.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/L3vL/intro_r_code/blob/main/03-Distribtion_Belgique.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["intro_R_sciences_sociales.pdf", "intro_R_sciences_sociales.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
